### ISSUE TITLE
403: 'Forbidden' error

### ISSUE THREAD

**Issue by kanishk-mehta** [fhellwig/graph-service#3]
I'm getting the following error:

```
{ HttpsError: [GET https://graph.microsoft.com:443/v1.0/users] Insufficient priv
ileges to complete the operation.
    at HttpsError (C:\Users\user.name\Documents\PROJECTS\CHATBOT\botbuilder-
nodejs\node_modules\https-error\https-error.js:215:9)
    at httpsError (C:\Users\user.name\Documents\PROJECTS\CHATBOT\botbuilder-
nodejs\node_modules\https-service\https-service.js:37:12)
    at IncomingMessage.response.on.e (C:\Users\user.name\Documents\PROJECTS\
CHATBOT\botbuilder-nodejs\node_modules\https-service\https-service.js:195:41)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) name: 'HttpsEr
ror', _code: 403, _text: 'Forbidden' }

```
 If there is any more information i need to provide, please let me know. I've checked and double checked my client ID and secret. Please help @fhellwig

**Comment by gciluffo** [comment]
@kanishk-mehta Pressing grant permissions for the application in Azure AD did it for me.

**Comment by fhellwig** [comment]
Looks like you figured it out... Yes, the application permissions must be set correctly independent of your client id/secret.
